language: go
go:
  - 1.7.3

# Don't want default ./... here:
install:
- go get -u github.com/govend/govend

- export PATH=$GOPATH/bin:$PATH
- mkdir -p $HOME/gopath/src/k8s.io

# (1) Fetch dependencies for us to run the tests in test/examples_test.go
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kubernetes.github.io
- go get -t -v k8s.io/kubernetes.github.io/test

# The dependencies are complicated, in that the libraries themselves import other packages.
# For example, we vendor in packages from apimachinery and client-go, but client-go itself vendors
# in apimachinery. This leads to conflicting versions in the two cases.
- pushd $PWD
- cd k8s.io/kubernetes.github.io/
- govend -v
- popd
#- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery
#- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/apiserver
#- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/client-go
#- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/sample-apiserver
#- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator
#- cp -r $GOPATH/src/k8s.io/kubernetes/vendor/* $GOPATH/src/
#- rm -rf $GOPATH/src/k8s.io/kubernetes/vendor/*
#- cp -r $GOPATH/src/k8s.io/kubernetes/staging/src/* $GOPATH/src/

# (2) Get md-check along with all its dependencies.
- git clone --depth=50 --branch=master https://github.com/kubernetes/md-check $HOME/gopath/src/k8s.io/md-check
- go get -t -v k8s.io/md-check

# (3) Fetch mungedocs
- go get -v k8s.io/kubernetes/cmd/mungedocs

script:
- go test -v k8s.io/kubernetes.github.io/test
- $GOPATH/bin/md-check --root-dir=$HOME/gopath/src/k8s.io/kubernetes.github.io
- ./verify-docs-format.sh
- $GOPATH/bin/mungedocs --verbose --verify --upstream=origin --root-dir=$HOME/gopath/src/k8s.io/kubernetes.github.io/docs/ --repo-root=$HOME/gopath/src/k8s.io/kubernetes.github.io --skip-munges=remove-whitespace,blank-lines-surround-preformatted,header-lines,sync-examples,analytics,analytics,kubectl-dash-f,table-of-contents,md-links,kubectl-dash-f
