language: go
go:
  - 1.7.3

# Don't want default ./... here:
install:
- go get -u github.com/govend/govend

- export PATH=$GOPATH/bin:$PATH
- mkdir -p $HOME/gopath/src/k8s.io

# (1) Fetch dependencies for us to run the tests in test/examples_test.go
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kubernetes.github.io
- go get -t -v k8s.io/kubernetes.github.io/test

# The dependencies are complicated, in that the packages we import in test/examples_test.go
# themselves import other packages that we also import.
# For example, we vendor in packages from apimachinery and client-go,
# but client-go itself vendors in apimachinery. This leads to conflict, which is why we blow away those dependencies
# from the vendor directories.
- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery
- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/apiserver
- rm $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/client-go

# (2) Get md-check along with all its dependencies.
- git clone --depth=50 --branch=master https://github.com/kubernetes/md-check $HOME/gopath/src/k8s.io/md-check
- go get -t -v k8s.io/md-check

# (3) Fetch mungedocs
- go get -v k8s.io/kubernetes/cmd/mungedocs

script:
- go test -v k8s.io/kubernetes.github.io/test
- $GOPATH/bin/md-check --root-dir=$HOME/gopath/src/k8s.io/kubernetes.github.io
- ./verify-docs-format.sh
- $GOPATH/bin/mungedocs --verbose --verify --upstream=origin --root-dir=$HOME/gopath/src/k8s.io/kubernetes.github.io/docs/ --repo-root=$HOME/gopath/src/k8s.io/kubernetes.github.io --skip-munges=remove-whitespace,blank-lines-surround-preformatted,header-lines,sync-examples,analytics,analytics,kubectl-dash-f,table-of-contents,md-links,kubectl-dash-f
