language: go
go:
  - 1.6.2

# Don't want default ./... here:
install:
- mkdir -p $HOME/gopath/src/k8s.io
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kubernetes.github.io
- go get -t -v $HOME/gopath/src/k8s.io/kubernetes.github.io
#- git clone https://github.com/kubernetes/md-check k8s
#- go get -t -v ./md-check

script: go test -v $HOME/gopath/src/k8s.io/kubernetes.github.io/test
